namespace Fauna2;

/// <summary>Idle revenue generated by restaurants and shops until the player collects it.</summary>
public static class RestaurantRevenue
{
	public static float MaxStored( PlaceableDefinition def ) =>
		def?.EffectiveMaxStoredRevenue ?? GameConstants.RestaurantMaxStored;

	public static float PerSecond( PlaceableComponent placeable )
	{
		var def = placeable?.Definition;
		if ( def?.ProvidesCollectibleRevenue != true )
			return 0f;

		if ( !PathNetwork.HasGuestAccess )
			return 0f;

		var guests = GuestSystem.Instance;
		if ( guests is null || guests.GuestCount <= 0 )
			return 0f;

		var coverage = CoverageFor( def, guests ) / 100f;
		if ( coverage <= 0f )
			return 0f;

		var satisfaction = GuestRevenue.SatisfactionMultiplier( guests.Satisfaction );
		var perMinute = def.EffectiveCollectIncomePerMinute
			* coverage
			* satisfaction
			* GuestRevenue.Multiplier;

		return GameConstants.AtGamePace( perMinute / 60f );
	}

	private static float CoverageFor( PlaceableDefinition def, GuestSystem guests )
	{
		if ( def.ProvidesRestaurant )
			return guests.RestaurantCoverage;

		if ( def.ProvidesShop )
			return guests.ShopCoverage;

		return 0f;
	}
}
